### ISSUE TITLE
Remove legacy code and align browser support with jQuery compat

### ISSUE THREAD

**Issue by timmywil** [jquery/sizzle#294]
Whether or not we have a branch that supports the same browsers as jQuery master is another issue. I think it may be an appropriate time to bring Sizzle master's browser support in line with jQuery compat. This means removing all legacy code that supports old browsers that jQuery compat will no longer support (including IE6/7).

**Comment by mzgol** [comment]
Note that we're [currently not testing against old Firefox/Chrome](https://github.com/jquery/sizzle/blob/a6ca3e9919c7a77001bdec01b3579e4bafd73a84/Gruntfile.js#L34-L37) so [the browser support list](https://github.com/jquery/sizzle/wiki#-browser-support) is not covered by tests. We should either add more browsers to testing (which, as we've seen, is problematic due to instability of Karma/BrowserStack) or change the list of officially supported browsers.

**Comment by mzgol** [comment]
(EDIT: disregard - I can't read)

**Comment by mzgol** [comment]
This is not written anywhere but this issue conclusion seems incorrect taking into account @gibson042's decision to keep current support and just offer custom builds excluding hacks for specific browsers in the future.

I've been putting up various commits for Sizzle today (mostly updating browsers in Karma & other build stuff) and I must say it was a real pain that Sizzle supports this many browsers. Karma tests are sometimes flakey, BrowserStack doesn't always work with many browsers spawned at the same time (and note you can't completely prevent it as two commits tested at the same time double the amount) so a lot of times something doesn't work as it should, tests also take a lot of time.

While I understand wanting to support more browsers than jQuery in Sizzle - e.g. supporting IE 6-7 & Opera 12.16, and maybe Safari 6.0 and last two Firefox ESRs (which makes 3-4 Firefox versions in total), I don't really see why test on:

1. Chrome 14
2. Firefox 3.6
3. Opera 11.6

and other similarly old browsers. No one uses them today and dropping testing on them would certainly make it easier to contribute.

**Comment by gibson042** [comment]
There is some redundancy, but also some quirks that are worth covering. I'd like to test only the newest and oldest browsers in normal runs, and carve off the middle into their own grunt task and weekly run à la jQuery (also to be run manually before releasing). Would you be willing to help with that?

**Comment by timmywil** [comment]
Ultimately, this is up to @gibson042, but I was thinking we'd start by removing any browsers from testing that are not supported in jQuery Compat and then see if there's any code we can remove without causing tests to fail.

**Comment by mzgol** [comment]
> There is some redundancy, but also some quirks that are worth covering.

What do you mean by "quirks that are worth covering"? What's the purpose of supporting Chrome 14, Opera 11.6 or Firefox 3.6?

> I'd like to test only the newest and oldest browsers in normal runs, and carve off the middle into their own grunt task and weekly run à la jQuery (also to be run manually before releasing). Would you be willing to help with that?

I can help with that. How do you imagine the weekly runs, though? Sizzle is tested entirely on Travis which, AFAIK, has only hooks for commits and you can't run weekly runs on it.

**Comment by markelog** [comment]
> has only hooks for commits and you can't run weekly runs on it.

You can trigger commits through API with some scheduler and would require server. But why would you want weekly builds? 

Seems pretty unnecessary, ci run is pretty fast already. We can cache the `node_modules` folder though :-)

**Comment by mzgol** [comment]
> Seems pretty unnecessary, ci run is pretty fast already.

It [runs for 6-7 minutes](https://travis-ci.org/jquery/sizzle/builds/76114008) if everything goes right (otherwise longer, like [15 minutes](https://travis-ci.org/jquery/sizzle/builds/76015184)) and sometimes gets flakey, triggers BrowserStack API errors etc. It was definitely a pain for me to wait for these runs to finish.

**Comment by mzgol** [comment]
> We can cache the node_modules folder though :-)

The main slowdown is from testing, not `npm install`. I.e. too many browsers.

**Comment by markelog** [comment]
I don't see not one commit when you changed the source, you needed to wait, since your changes are only about updating browser versions (instead of creating package that would do that automatically :-) so you need to wait until ci is finishes.

@timmywil and @gibson042 actually never report CI failures, when they were happening. Usual workflow is you commit, then forget about it, if something is wrong, ci will notice you, that is why, travis, for example, send you an email only when you release or when something was wrong.

5-15 minutes is actually nothing, C++ devs would laugh in your face if say something like to them :-). That is where "nightly builds" expression come from.

No, of course, if you want to, you can keep cron job on running server, change the build logic and complicate lots of other stuff.

No one ever does this with travis, we would be the first.

**Comment by mzgol** [comment]
> I don't see not one commit when you changed the source, you were needed to wait, since your changes are only about updating browser versions (instead of creating package that would do that automatically :-) so you need to wait until ci is finishes.

It's not just about waiting; when I submitted a PR from the upstream branch so that all browsers are tested, there are two Travis runs scheduled - one for the PR and one for the upstream branch; both run on all browsers (perhaps it'd be wise to never run tests on all browsers on PRs since the branch testing covers that already). This created a lot of browsers connecting simultaneously and a lot of 403 messages from BrowserStack, breaking the build. I had to restart those jobs individually later, making sure nothing else runs. Far from ideal.

There's a change 6e8f617f32cd399cb558b5c36fcd9532a2164b1c will help, we'll see. Or we'll have to split the browser matrix even further to prevent 15 browsers from connecting at the same time.

> @timmywil and @gibson042 actually never report CI failures, when they were happening. Usual workflow is you commit, then forget about it, if something is wrong, ci will notice you, that is why, travis, for example, send you an email only when you release or when something was wrong.

BrowserStack has implemented polling limits fairly recently so setups that didn't fail in the past may very well be failing now. I have experienced it. Before my yesterday's commits there haven't been any since April so the problems might not have been visible in the meantime.

> 5-15 minutes is actually nothing, C++ devs would laugh in your face if say something like to them :-). That is where "nightly builds" expression come from btw.

It's more about builds breaking than taking 15 minutes. But, again, maybe 6e8f617f32cd399cb558b5c36fcd9532a2164b1c will help.

Although the latter, too. The fact that some people have it worse doesn't mean we need to aim to reach the same state...

**Comment by markelog** [comment]
>  I submitted a PR from the upstream branch so that all browsers are tested, there are two Travis runs scheduled - one for the PR and one for the upstream branch; both run on all browsers 

Don't do that, just use your own fork and your own browserstack key.

> BrowserStack has implemented polling limits fairly recently so setups that didn't fail in the past may very well be failing now.

That should have little effect on our situation, since we run browsers sequentially.

> The fact that some people have it worse doesn't mean we need to aim to reach the same state...

I'm not saying we should "aim", i'm saying you don't need to look at CI results, you commit and remember about CI only if you have a failure.

I would run CI for thousands hours on one commit, if it would mean we would have less bugs. 

Proposition for complication of build logic and adding point of failure, to make CI be couple minutes faster is... weird. That thing with "weekly" stuff, front-end projects don't usually do that, in fact i know only one project that does - core.

Weekly or Daily stuff it is a "nightly builds" because on projects like C++ (since i already made that analogy i should stick to it) projects could run days on the CI, do this because we have our 15 minutes, is, again, weird as hell.

**Comment by gibson042** [comment]
The current structure of Sizzle is such that fixing glitches in old browsers takes very little code. Couple that with its dubious utility for modern browsers (mostly enabling the ability to express slow-running selectors), and it encourages supporting a wide swath of old technology because that's where the problem space lies. But doing so makes testing much more burdensome, which I'd like to address.

I'm comfortable with doing a full run manually before each release, but Travis offers [on-demand builds](http://docs.travis-ci.com/user/triggering-builds/) with custom environment variables that https://github.com/jquery/sizzle/blob/master/test/karma/environment.js could use (e.g., fast Travis-local testing of every PR, moderate BrowserStack testing of every branch, full BrowserStack testing only of API-initiated runs against our master). It's all about responsiveness.

**Comment by mzgol** [comment]
>>  I submitted a PR from the upstream branch so that all browsers are tested, there are two Travis runs scheduled - one for the PR and one for the upstream branch; both run on all browsers 
>
> Don't do that, just use your own fork and your own browserstack key.

How? If I submit PRs from my fork, BrowserStack isn't used. Do you suggest modifying the secret keys for the PR?

>> BrowserStack has implemented polling limits fairly recently so setups that didn't fail in the past may very well be failing now.
>
> That should have little effect on our situation, since we run browsers sequentially.

We run tests [in 17 browsers at the same time](https://github.com/jquery/sizzle/blob/b13175592caf248ce215d761a7ad50cd054fb88f/Gruntfile.js#L34-L47), it was definitely failing for me on the Sizzle repo.

> Proposition for complication of build logic and adding point of failure, to make CI be couple minutes faster is... weird. That thing with "weekly" stuff, front-end projects don't usually have that, in fact i know only one project that does - core.

And it's very useful in Core, we finally have green builds that don't take ages. But yeah, Sizzle is different in that it has tremendously fewer tests than jQuery.

**Comment by mzgol** [comment]
> The current structure of Sizzle is such that fixing glitches in old browsers takes very little code. Couple that with its dubious utility for modern browsers (mostly enabling the ability to express slow-running selectors), and it encourages supporting a wide swath of old technology because that's where the problem space lies.

I agree with that point, mine was that we could limit this to old browsers that have a chance of people actually using them. Which is the case for IE6-7 (enterprise usage), Opera 12.16 (last Presto Opera which never got automatically updated to the Blink line) but I don't believe it's the case for e.g. Firefox 3.6 or Opera 11.6.

Also, for the case of jQuery & jQuery Compat it would be useful to not carry that old browser baggage - but I understand that's planned to resolve and just requires time.

That said, I don't care too much if regular runs are tested on a subset of browsers and full runs only periodically or before releases.

**Comment by gibson042** [comment]
>> Don't do that, just use your own fork and your own browserstack key.

> How? If I submit PRs from my fork, BrowserStack isn't used. Do you suggest modifying the secret keys for the PR?

Environment variables: `BROWSER_STACK_USERNAME=… BROWSER_STACK_ACCESS_KEY=… grunt --force build karma:phantom karma:desktop …`

**Comment by markelog** [comment]
@gibson042

> but Travis offers on-demand builds with custom environment variables that https://github.com/jquery/sizzle/blob/master/test/karma/environment.js could use (e.g., fast Travis-local testing of every PR

You would need a server for this, see above. 

> fast Travis-local testing of every PR

I would just made those keys public, lots projects already do that. Test that stuff automatically.

> It's all about responsiveness.

I see it like that - you made changes to fix android bug? Run tests only in android `grunt test --browsers=bs_android-4.0`. 

Then make a PR, which would run everything on everything, so you notice the issue with ios 5 right away, and don't wait for week after pr was landed and trashed the commit history.

@mzgol
> We run tests in 17 browsers at the same time,

So lets divide them on smaller groups.

> And it's very useful in Core, we finally have green builds that don't take ages.

We have green builds, that was primary reason, at least for me.

**Comment by mzgol** [comment]
@gibson042 
> Environment variables: `BROWSER_STACK_USERNAME=… BROWSER_STACK_ACCESS_KEY=… grunt --force build karma:phantom karma:desktop …`

Ah, locally. I thought the remark was about making those tests run in the PR. OK then.

@markelog 
> I would just made those keys public, lots projects already do that. Test that stuff automatically.

I recall BrowserStack was against making their keys public; Sauce Labs was not. We'd need to get BrowserStack to agree or use Sauce Labs for PRs. But I agree in principle.

**Comment by markelog** [comment]
Well, yeah, but i remember other devs do that, so we should be in the clear

**Comment by nazar-pc** [comment]
What is current status here, taking into account that jQuery Compat is already dead before even being released?

**Comment by HolgerJeromin** [comment]
Removing support for some rotten browsers would reduce such reports:
https://github.com/jquery/jquery/issues/3923, https://github.com/jquery/jquery/issues/3551

https://github.com/jquery/sizzle/blob/3116795bba9a0c3d624e0718006b25aa5568d4cb/src/sizzle.js#L816-L818

I develop my App with "catch all exception" so i would like to get rid of this line, even if this is still valid:
https://github.com/jquery/sizzle/blob/3116795bba9a0c3d624e0718006b25aa5568d4cb/src/sizzle.js#L833-L836

**Comment by mgol** [comment]
This is probably not going to happen. Instead, we're going to remove the Sizzle dependency from jQuery and go from there.
