### ISSUE TITLE
Sizzle throws exception when id selector has a leading dot

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [jquery/sizzle#320]
Example:

```javascript
// Syntax error, unrecognized expression: #.
Sizzle( "#." );
```

**Real use case**

[AddThis](http://support.addthis.com/customer/portal/articles/381252-click-tracking) uses a click tracking mechanism that uses the hashbang to detect sharing.
It is expected that when you lookup a hashbang for a DOM element it just fails silently if the element is not found:

```javascript
$( "#" + window.location.hash.replace( /^#\/?/, "" ) );
```

But if you use AddThis, it adds the following hashbang in the url:

```
http://localhost/page#.VPrIoGTO1W4.facebook
```

Notice the leading dot. In this case the code will throw an exception instead of returning zero elements because of the dot in the beginning.

**Comment by arthurvr** [comment]
That's because `.` is reserved in CSS selectors. You can refer to [this article in the learning center](http://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/). That article also contains a function that escapes it automatically.

Side: this is the native behaviour as well. http://gyazo.com/88013605a61af3625c9de6c361e27c07

**Comment by FagnerMartinsBrack** [comment]
Despite this being a native behavior I couldn't find in the spec anything saying that a leading dot is not allowed in a query selector. This breaks a basic expectation of jquery being no-op and chainable for an empty array of elements.

**Comment by timmywil** [comment]
Thank you for opening an issue, but the dot needs to be escaped. http://api.jquery.com/category/selectors/

**Comment by FagnerMartinsBrack** [comment]
https://github.com/jquery/sizzle/pull/321#issuecomment-77690191

err... I was aware of the special tokens, but never thought it would throw an error.
Another DOM trap, sorry for the noise.
