### ISSUE TITLE
Confused about a piece of code

### ISSUE THREAD

**Issue by gdut-zdc** [jquery/sizzle#327]
What's the function of the code " || sofar " ? Under what circumstances, the code " soFar.slice( match[0].length ) " will return false?
<pre>
tokenize = Sizzle.tokenize = function( selector, parseOnly ) {
	var matched, match, tokens, type,
		soFar, groups, preFilters,
		cached = tokenCache[ selector + " " ];

	if ( cached ) {
		return parseOnly ? 0 : cached.slice( 0 );
	}

	soFar = selector;
	groups = [];
	preFilters = Expr.preFilter;

	while ( soFar ) {

		// Comma and first run
		if ( !matched || (match = rcomma.exec( soFar )) ) {
			if ( match ) {
				// Don't consume trailing commas as valid
				soFar = soFar.slice( match[0].length ) || soFar;
			}
			groups.push( (tokens = []) );
		}

		matched = false;
</pre>

**Comment by gibson042** [comment]
As the preceding comment indicates, we don't want to accept selectors with trailing commas (e.g., "foo,bar,"). So in cases where consuming the comma with `slice` leaves an empty string, we simply revert that operation by restoring the unmodified value.

Thank you for your interest, but please ask further questions in [IRC](http://irc.jquery.org/) rather than opening an issue.
