### ISSUE TITLE
Sizzle.attr(el, name) returns empty string for not defined 'formnovalidate' attribute

### ISSUE THREAD

**Issue by alex-simonov** [jquery/sizzle#331]
In IE 11 without emulation (Edge mode) and with emulation of IE9 and IE10 button text will be "OK". 
If I turn on IE8 emulation mode then button text will be "Error", because `$button.attr("formnovalidate")` returns empty string.

    <body>
      <button id="button" type="button"></button>
      <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
      <script>
        $(function () {
            var $button = $('#button');
            $button.text($button.attr("formnovalidate") !== undefined ? "Error" : "OK");
        });
      </script>
    </body>

I think that you should check `elem.hasAttribute( name )` before calling ` elem.getAttribute( name )` [here](https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L916).

**Comment by gibson042** [comment]
This appears to be a bug in IE10–11 emulation of IE8, since your code works as expected on the real browser: http://jsfiddle.net/xv58kevd/show/light/

Presumably, knowledge of `novalidate` and `noformvalidate` boolean attributes is erroneously preserved. Regardless, we're not inclined to fix bugs specific to emulation mode. You can fix it yourself by adding new properties to attrHandle, though (e.g., `$.expr.attrHandle.noformvalidate = $.expr.attrHandle.hidden`).
