### ISSUE TITLE
pseudo contains uses innerText

### ISSUE THREAD

**Issue by Mottie** [jquery/sizzle#335]
Currently, the contains pseudo selector uses the following code:

``` js
return ( elem.textContent || elem.innerText || getText( elem ) ).indexOf( text ) > -1;
```

The [notoriously slow `innerText` function](http://www.kellegous.com/j/2013/02/27/innertext-vs-textcontent/) is not used anywhere else in the code and would only add more delay to processing if `textContent` happened to return an empty string. 

``` js
return ( elem.textContent || getText( elem ) ).indexOf( text ) > -1;
```

There was no significant change in the speed tests after removing the `innerText` function. I think the significance would be obvious with more empty elements targeted by the selector.

**Comment by dmethvin** [comment]
To reach that "notoriously slow" case you'd need to be updating the content in the same turn before reading the text, and I'm not convinced that is common at all. Also, `innerText` is actually [more useful and intutive than `textContent`](http://perfectionkills.com/the-poor-misunderstood-innerText/) in what it returns, precisely because it has some knowledge of layout. 

I think you could make the case for avoiding `innerText` for reasons of consistency though, since `getText()` acts more like `textContent`.

**Comment by gibson042** [comment]
I'm interested in seeing a [jsPerf](http://jsperf.com/) comparison of this change vs. current behavior for IE<9, testing them against both empty elements and elements containing deep structure. Depending on how it looks, we might even _always_ invoke `getText` for `:contains` instead of duplicating its property checks. Would you be willing to put one together, @Mottie?

**Comment by Mottie** [comment]
Ok, I created [this jsPerf](http://jsperf.com/sizzle-contains), but I don't have access to IE<9, and I don't think running IE11 in compatibility mode would suffice. And I have yet to learn how to use browserstack.

**Comment by gibson042** [comment]
That's not quite right. I want _deep_ structure, so `getText` has to recurse. And I want a clear separation between cases that run against empty nodes and non-empty nodes, to compare the effects of the change on each independently. http://jsperf.com/sizzle-contains is a good start, though, and can be modified. It'll be great if you can do it, but otherwise I'll probably pick it up later this week.

**Comment by Mottie** [comment]
Alright, I've updated the demo: http://jsperf.com/sizzle-contains/2

I'm not really sure what to make of the results... Firefox & older IE (compatibility mode) is showing worse performance overall.

**Comment by gibson042** [comment]
Thank you. I also tried a variation with visible fixtures, yielding similar results: http://jsperf.com/sizzle-contains/3

The IE8 performance in particular disinclines me towards removing `innerText` completely, but there's no denying that it has edge-case differences from `textContent` & `getText`. And since performance already drops from mere _inclusion_ of something like `:contains`, and `getText` uses `textContent` anyway, we might as well go all-in with something like
```js
return getText( elem ).indexOf( text ) > -1;
```

**Comment by Mottie** [comment]
There is a significant difference in speed when the `textContent` is completely removed: http://jsperf.com/sizzle-contains/4

**Comment by gibson042** [comment]
Yeah, function invocation can be expensive. But so can the other operations, so it's worth playing around here.

**Comment by gibson042** [comment]
I checked again, and have resolved to use the original suggestion (`elem.textContent || getText( elem )`).

**Comment by SaptakS** [comment]
@gibson042 so if I am not wrong we need to replace the `return ( elem.textContent || elem.innerText || getText( elem ) ).indexOf( text ) > -1;` with `return ( elem.textContent || getText( elem ) ).indexOf( text ) > -1;` because the innerText makes the things slow, right? Correct me if I am wrong. Would like to solve this issue.
