### ISSUE TITLE
Depends on a global "document"

### ISSUE THREAD

**Issue by matthewp** [jquery/sizzle#343]
jQuery has the ability to return a function when a document doesn't exist so that you can provide your own document (such as in Node).  However Sizzle makes this functionality not work, because it does expect a global document [here](https://github.com/jquery/sizzle/blob/master/dist/sizzle.js#L360).

**Comment by gibson042** [comment]
That's not the global document; see [`setDocument`](https://github.com/jquery/sizzle/blob/master/dist/sizzle.js#L502).

**Comment by matthewp** [comment]
I understand closing a PR as incorrect but why would you close an issue without getting clarity on the problem?

I posted this in the (closed) PR issue but jQuery allows itself to be ran in an environment without a document by passing in a window object that has a document.  So you can do this:

```js
var makejQuery = require("jquery");

var jQuery = makejQuery(myFakeWindow);
```

jQuery supports this. Sizzle does not, so it breaks.  I apologize for the incorrect fix, any advise on what needs to be done to fix this would be appreciated.

**Comment by gibson042** [comment]
My apologies; this looked like a non-issue. It still may be, but the above is insufficient to properly assess... what is `myFakeWindow`, what call throws an exception, and how is Sizzle responsible?

jQuery itself guarantees [something very similar](https://github.com/jquery/jquery/blob/9d820fbde6d89bc7a06e2704be61cf6c0b4d6e3c/test/node_smoke_tests/document_passed.js), and I just manually confirmed that basic Sizzle functionality remains operative in such an environment. Please provide a more complete test case demonstrating what you want to do and where it fails (a Node.js script will be just fine—sorry for suggesting the obviously inapplicable JS Bin), and I'll happily take a deeper look.

**Comment by mzgol** [comment]
Regardless of this particular issue, jQuery now doesn't assume the browser environment by declaring globals explictely in [its .jshintrc](https://github.com/jquery/jquery/commit/76df9e4e389d80bff410a9e5f08b848de1d21a2f#diff-b7ac5ae82f282a9e6768c835add5edfd) instead of just using `"browser": true`. Such a change is not present in [Sizzle's src/.jshintrc](https://github.com/jquery/sizzle/blob/a6ca3e9919c7a77001bdec01b3579e4bafd73a84/src/.jshintrc#L19) and it should.

**Comment by matthewp** [comment]
> My apologies; this looked like a non-issue. It still may be, but the above is insufficient to properly assess... what is myFakeWindow, what call throws an exception, and how is Sizzle responsible?

This is a difficult question to answer because what I am attempting to do is figure out how much of the DOM API Sizzle needs to load.  I don't expect you to know the answer to this question.  So to start off with I gave it this:

```
var makeFakeWindow = {
  document: {}
};
```

Again, **I expect this to fail**.  I just don't expect it to fail for the reason of document being undefined. Document is **not** undefined.

[This line](https://github.com/jquery/sizzle/blob/master/dist/sizzle.js#L360) is where the exception occurs.

**Comment by gibson042** [comment]
Thanks; that clears things up. Let me preface the following by pointing out that Sizzle is a _DOM_ library and is useless without an essentially complete implementation. In fact, we assume certain baseline aspects, which are not documented and are subject to change at any time. Failure to even load when those assumptions are violated is **not** a bug. Further, it looks like you're trying to load not Sizzle, but jQuery (normal builds of which include Sizzle). The distinction is relevant, which I'll get to shortly. But I'm going to unequivocally recommend that you use a DOM library like [jsdom](https://github.com/tmpvar/jsdom) rather than trying to bare-minimum your own.

That said, the current minimum "window" required to load Sizzle without exceptions—_invocation_ being another story, though—looks like this:
```js
{
  document: {
    documentElement: {},
    nodeType: 9,
    createElement: function() { return {}; }
  }
}
```
...which is _still_ not enough to load jQuery. For that, you'll need
```js
{
  document: {
    documentElement: {},
    implementation: {
      createHTMLDocument: function () {
        return {
          body: {
            childNodes: []
          }
        };
      }
    },
    nodeType: 9,
    addEventListener: function(){},
    createDocumentFragment: function () {
      return { appendChild: this.createElement };
    },
    createElement: function createElement() {
      var el = {};
      el.lastChild = el;
      el.appendChild = el.cloneNode = el.setAttribute = createElement;
      return el;
    }
  },
  location: {},
  addEventListener: function(){}
}
```
**ALL** of which, again, is sufficient _only_ for loading and _only_ as of this point in time.

**Comment by matthewp** [comment]
Thanks!
