### ISSUE TITLE
elem.getAttribute( name ) not working with Document Fragment

### ISSUE THREAD

**Issue by h7896v7347** [jquery/sizzle#357]
In connection with VueJS Router + uikit JS, 
when Route is changed, after click trigger **inside** destroyed Document Fragment

**Uncaught TypeError: elem.getAttribute is not a function**
is shown on line https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L915 

elem 
``#document-fragment
baseURI: null
childElementCount: 1
childNodes: NodeList[4]
children: HTMLCollection[1]
firstChild: comment
firstElementChild: div.tm-full-width
lastChild: comment
lastElementChild: div.tm-full-width
localName: null
namespaceURI: null
nextSibling: null
nodeName: "#document-fragment"
nodeType: 11
nodeValue: null
ownerDocument: document
parentElement: null
parentNode: null
previousSibling: null
textContent: "↵ ↵↵ 
__proto__: DocumentFragment``

**Adding "dirty fix"**

``if(elem.nodeName == "#document-fragment")
		 {
		 	elem = elem.firstElementChild ;
		 }``
before
``return val !== undefined ?``
seems to fix it, but i don't think this is the best solution.

**Comment by dmethvin** [comment]
Do you have a test case? Why is a click being triggered after something is destroyed?

**Comment by h7896v7347** [comment]
It's in larger internal App, i will try recreate it 

uikit JS is trigering it in this lines:
https://github.com/uikit/uikit/blob/master/src/js/core/smooth-scroll.js#L10 
https://github.com/uikit/uikit/blob/master/src/js/core/alert.js#L16

It may be problem with some unstoped propagation in vuejs/uikit.
 It was quick fix, after JS for uikit was added to app and killed it.

**Comment by gibson042** [comment]
This is not a Sizzle problem, but it is a jQuery problem if the outer library is still sending in non-elements. That _should_ have been fixed by https://github.com/jquery/jquery/commit/9d820fbde6d89bc7a06e2704be61cf6c0b4d6e3c (master) and https://github.com/jquery/jquery/commit/fc2ba2e1361126c39f955437ee025cfca3bffa65 (compat), but I see that the former has not made it into a release yet. Assuming you're using a 2.x version, can you verify that the [git build](http://code.jquery.com/jquery-git.js) does not exhibit this problem?

**Comment by h7896v7347** [comment]
You are absolutely right, 
v3.0.0-pre 99e8ff1baa7ae341e94bb89c3e84570c7c3ad9ea 
solves the problem.
