### ISSUE TITLE
inconsistent behavior between find('input:invalid') and find('input').filter(':invalid')

### ISSUE THREAD

**Issue by clayzermk1** [jquery/sizzle#371]
It seems that sizzle will let me do a find for invalid inputs just fine (despite not supporting the `:invalid` pseudo selector officially?) but throws an error when I try to filter for invalid inputs.

I cooked up a [fiddle](https://jsfiddle.net/clayzermk1/j9wyemrr/), I have the values going to the console.

I'm using:
jQuery 2.1.4
Chrome 46.0.2490.86 (64-bit)
OS X 10.9.5 (13F1112)

Thank you for your time!

**Comment by timmywil** [comment]
Thanks for opening an issue. This is not actually an issue with jQuery, since `:invalid` is not a supported selector. Plugins like jquery.validate will add support for this pseudo, and jQuery will try to pass any selector through QSA first, but while `input:invalid` is a valid selector and works with QSA, `:invalid` is not, and breaks because Sizzle does not support it. Support for this selector is best left to validation plugins that have all the logic to validate inputs.

**Comment by clayzermk1** [comment]
@timmywil Thank you for the reply and explanation. I am aware that jQuery does not support these pseudo classes (I'm not asking for support or anything like that). I wasn't trying to imply there was something wrong with jQuery, only that I would expect it to not work (throw an error, for example) in all cases instead of working in an inconsistent fashion.

I have found that the similar `.find('input').filter('input:invalid')` also throws the error as demonstrated in [this fiddle](https://jsfiddle.net/clayzermk1/Ltyd0hwb/).

By QSA I assume you mean `document.querySelectorAll()`? If so, it seems to handle `:invalid` just fine on Chrome as demonstrated by [this fiddle](https://jsfiddle.net/clayzermk1/r5qcoyjb/).

Just thought it was weird. Thanks again for your time. Cheers :beers:!
