### ISSUE TITLE
Unset ID attribute bug

### ISSUE THREAD

**Issue by mclov1n** [jquery/sizzle#394]
Applying any sizzle selector to an element with unset id (the attribute "id" exists on the DOM element but with not any value) will remove the id attribute. Any later attempt to acquire the attribute "id" (".attr('id')") would result to 'undefined' which is wrong since the "id" attribute initially existed.
Going through the code i noticed that an intermediate "id" attribute is used (sizzle-something) for elements of which the '.getAttribute("id")' condition evaluates to false. The intermediate id is set to the element as an attribute and when work is done is being removed. However, that removes the initial id attribute entry  of the element as well (which had no value). 
Maybe the 'hasAttribute' function should have been used.

**Comment by mgol** [comment]
From https://html.spec.whatwg.org/#global-attributes:
> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character.

Therefore, an HTML with an empty `id` value is invalid HTML and, hence, unsupported by Sizzle.

**Comment by mclov1n** [comment]
That, in turn, means that all invalid html are unsupported by jQuery as well (since sizzle is part of it) ?

**Comment by mgol** [comment]
Yes, that's true, jQuery only officially supports valid HTML.

**Comment by mclov1n** [comment]
Since jQuery is widely used and invalid html as well, shouldn't it be based on the 'best working scenario' so as to try and solve those discrepancies ?

**Comment by mgol** [comment]
There are lots of things that can go wrong if you use invalid HTML, e.g. if you have two elements with the same ID `foo`, `$('#foo')` will get you only one of them while `document.querySelectorAll('#foo')` would give you both. It'd be too hard to support every invalid use case and in many cases it wouldn't even be possible due to the internal preprocessing. It's simpler to just assume we don't take responsibility for invalid markup.

It's not that jQuery will completely fail if you have invalid markup but that you can experience problems related to it. In this case, you have invalid ID value so Sizzle handles the ID in a way you don't expect.

**Comment by mclov1n** [comment]
I can see your point and thanks for your responses.
On a final note, can you please give me more details or a starting point to search for what you mention as 'internal preprocessing'.
