### ISSUE TITLE
Is this project Dead ?

### ISSUE THREAD

**Issue by varunsridharan** [jquery/sizzle#473]
Well i am planing on using this library but can't find any recent changes to it.

Is this project dead ?

**Comment by mgol** [comment]
The latest commit is from March this year, not quite dead, is it? 😉

However, Sizzle is now mostly used as a selector engine for jQuery 3.x & we focus on issues affecting jQuery which there are not too many. Other use cases are de-prioritized so we’re not focusing on Sizzle development that much.

jQuery 4 will not use Sizzle anymore. When we stop supporting jQuery 3.x (which will most likely take a few years) we’re likely to stop maintaining Sizzle as well.

Hopefully that answers your questions.

**Comment by varunsridharan** [comment]
@mgol thanks for your quick answer. well i did not see the recent comment instead i checked the releases. 

Well i am planing on using Library. and did checked V4.0's source code from jquery/jquery and found that sizzle has migrated. if possible would like to know if there are any major changes done to it. ?

**Comment by mgol** [comment]
The biggest changes for now are removing workarounds for legacy browsers. Our future plans involve dropping support for positional selectors like `:first` or `:even` & doing a significant refactor that will depend more on `querySelectorAll`, only rewriting those selector paths that need it instead of doing a full fallback to manual traversing which we plan to remove. So, big changes are planned but it’s not clear yet whether we’ll be able to achieve them all in time for jQuery 4.0.

**Comment by varunsridharan** [comment]
@mgol awesome :-)
Thanks for your quick reply.

**Comment by varunsridharan** [comment]
@mgol i just wanted to share my project with you guys since its related to this
https://github.com/varunsridharan/dizzle
